/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cg;

public class Queue {
	private LinkedList list;

	public Queue() {
		list = new LinkedList();
	}

	public void enqueue(INode node) {
		list.append(node);
	}

	public INode dequeue() {
		return list.pop();
	}

	public int getSize() {
		return list.size();
	}

	public String toString() {
		return list.toString();
	}
}
